#server:
#  port: 8099
#eureka相关配置
eureka:
  client:
    #是否将自己注册在EurekaServer上，默认为true。由于当前应用就是EurekaServer，所以置为false
    register-with-eureka: true
    #是否从EurekaServer获取注册信息，默认为true。单节点不需要同步其他的EurekaServer节点的数据
    fetch-registry: true
    #设置Eureka的地址
    service-url:
      defaultZone: http://yidu:yidu123@127.0.0.1:8098/eureka/
instance:
        instance-id: eurekeServer8099
        prefer-ip-address: true #将自己的ip地址注册到Eureka服务中
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 3000

spring:
  security:
    user:
      name: yidu
      password: yidu123