server:
  port: 8080
  servlet:
    context-path: /yidu

spring:
  datasource:
    name: test
    url: jdbc:mysql://127.0.0.1:3306/yidu_product_db?serverTimezone=Hongkong
    username: root
    password: 123
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: yidu_product_microService #微服务名字

mybatis:
  mapper-locations: classpath:config/mapping/*.xml
  type-aliases-package: com.yidu.product.entity
eureka:
  client:
    register-with-eureka: true #是否将自己注册到Eureka服务中，默认为true
    fetch-registry: true #是否从Eureka中获取注册信息，默认为true
    service-url:
      defaultZone: http://localhost:8099/eureka #Eureka客户端与Eureka服务端进行交互的地址,**注意defaultZone没有提示,需要手动加上**
  instance:
    prefer-ip-address: true #将自己的ip地址注册到Eureka服务中,也就是说路径可以显示ip
    instance-id: product-info # 服务名字
