server:
  port: 8081
  servlet:
    context-path: /yidu
spring:
  datasource:
    name: test
    url: jdbc:mysql://127.0.0.1:3306/yidu_product_db?serverTimezone=Hongkong
    username: root
    password: 123
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: yidu_order_microService #微服务名称
mybatis:
  mapper-locations: classpath:config/mapping/*.xml
  type-aliases-package: com.yidu.order.entity

eureka:
  client:
    registerWithEureka: false #是否将自己注册到Eureka服务中，默认为true
    fetchRegistry: true #是否从Eureka中获取注册信息，默认为true
      serviceUrl: #Eureka客户端与Eureka服务端进行交互的地址
        defaultZone: http://127.0.0.1:8099/eureka/
